[package]
name = "bmcc"
version = "0.1.0"
edition = "2015"

[dependencies]
chumsky = { version = "1.0.0-alpha.7" }
codesnake = "0.2.1"
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
yansi = "1.0.1"
